In [12]:
import numpy as np
from scipy import stats

# File input/output: scipy.io

### Loading and saving matlab files:

In [2]:
from scipy import io as spio

In [4]:
a = np.ones((3, 3))
a

array([[ 1.,  1.,  1.],
       [ 1.,  1.,  1.],
       [ 1.,  1.,  1.]])

In [6]:
spio.savemat('file/file.mat', {'a': a})

In [7]:
data = spio.loadmat?

In [8]:
# Load MATLAB file.
data = spio.loadmat('file/file.mat', struct_as_record=True)

In [9]:
data['a']

array([[ 1.,  1.,  1.],
       [ 1.,  1.,  1.],
       [ 1.,  1.,  1.]])

In [10]:
data['b']

KeyError: 'b'

### Reading images

In [13]:
from scipy import misc

In [14]:
misc?

In [20]:
misc.imread('image/exercice_2.png')

AttributeError: 'module' object has no attribute 'imread'

In [18]:
import matplotlib.pyplot as plt

In [21]:
plt.imread('image/exercice_2.png')

array([[[ 1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.],
        ..., 
        [ 1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.]],

       [[ 1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.],
        ..., 
        [ 1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.]],

       [[ 1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.],
        ..., 
        [ 1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.]],

       ..., 
       [[ 1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.],
        ..., 
        [ 1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.]],

       [[ 1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.],
        ..., 
        [ 1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.]],

       

__NOTE__

error when open image with suffixes is not '.png'

```
ValueError: Only know how to handle extensions: ['png']; with Pillow installed matplotlib can handle more images
```

```text
See also:
Load text files: numpy.loadtxt()/numpy.savetxt()
Clever loading of text/csv files: numpy.genfromtxt()/numpy.recfromcsv()
Fast and efficient, but numpy-specific, binary format: numpy.save()/numpy.load()

```