In [1]:
import numpy as np
import scipy as sp
import matplotlib.pyplot as plt
%matplotlib inline

### Life of ndarray

## Block of memory

In [2]:
x = np.array([1, 2, 3], dtype=np.int32)
x

array([1, 2, 3], dtype=int32)

In [3]:
x.data

In [4]:
str(x.data)

'<memory at 0x7f4ed6b6cd90>'

```
Memory address of the data:
```

In [5]:
x.__array_interface__['data'][0]

55740704

In [6]:
x.__array_interface__

{'data': (55740704, False),
 'descr': [('', '<i4')],
 'shape': (3,),
 'strides': None,
 'typestr': '<i4',
 'version': 3}

In [7]:
x = np.array([1, 2, 3, 4])
x

array([1, 2, 3, 4])

In [8]:
y = x[:-1]
y

array([1, 2, 3])

In [9]:
x[0] = 9
x

array([9, 2, 3, 4])

In [10]:
y

array([9, 2, 3])

In [11]:
id(x), id(y), x.__array_interface__, y.__array_interface__

(139976585682576,
 139976582742304,
 {'data': (50338272, False),
  'descr': [('', '<i8')],
  'shape': (4,),
  'strides': None,
  'typestr': '<i8',
  'version': 3},
 {'data': (50338272, False),
  'descr': [('', '<i8')],
  'shape': (3,),
  'strides': None,
  'typestr': '<i8',
  'version': 3})

In [12]:
x = b'1234'  # 'b' is for "bytes", necessary in Python3

In [13]:
x

b'1234'

```
x is a string (in Python 3 a bytes), we can represent its data as an array of ints:
```

In [14]:
y = np.frombuffer?

In [ ]:
y = np.frombuffer

In [15]:
# Interpret a buffer as a 1-dimensional array.
y = np.frombuffer(x, dtype=np.int8)
y

array([49, 50, 51, 52], dtype=int8)

In [16]:
y.data

In [17]:
y.base is x

True

In [18]:
y.flags

  C_CONTIGUOUS : True
  F_CONTIGUOUS : True
  OWNDATA : False
  WRITEABLE : False
  ALIGNED : True
  UPDATEIFCOPY : False

In [19]:
y.__array_interface__

{'data': (139976585532512, True),
 'descr': [('', '|i1')],
 'shape': (4,),
 'strides': None,
 'typestr': '|i1',
 'version': 3}

```
The owndata and writeable flags indicate status of the memory block.
```

### Data types

##### The descriptor

```
dtype describes a single item in the array:
```

In [20]:
np.dtype(int)

dtype('int64')

In [21]:
np.dtype(int).type # scalar type of the data

numpy.int64

In [22]:
np.dtype(int).itemsize # size of the data block

8

In [23]:
np.dtype(int).byteorder

'='