In [4]:
import numpy as np
import scipy as sp
import matplotlib.pyplot as plt
%matplotlib inline

### Life of ndarray

## Block of memory

In [6]:
x = np.array([1, 2, 3], dtype=np.int32)
x

array([1, 2, 3], dtype=int32)

In [8]:
x.data

In [9]:
str(x.data)

'<memory at 0x7ff8c537dd90>'

```
Memory address of the data:
```

In [18]:
x.__array_interface__['data'][0]

31134544

In [19]:
x.__array_interface__

{'data': (31134544, False),
 'descr': [('', '<i4')],
 'shape': (3,),
 'strides': None,
 'typestr': '<i4',
 'version': 3}

In [21]:
x = np.array([1, 2, 3, 4])
x

array([1, 2, 3, 4])

In [22]:
y = x[:-1]
y

array([1, 2, 3])

In [24]:
x[0] = 9
x

array([9, 2, 3, 4])

In [25]:
y

array([9, 2, 3])

In [28]:
id(x), id(y), x.__array_interface__, y.__array_interface__

(140706433741168,
 140706433740848,
 {'data': (34344864, False),
  'descr': [('', '<i8')],
  'shape': (4,),
  'strides': None,
  'typestr': '<i8',
  'version': 3},
 {'data': (34344864, False),
  'descr': [('', '<i8')],
  'shape': (3,),
  'strides': None,
  'typestr': '<i8',
  'version': 3})

In [29]:
x = b'1234'  # 'b' is for "bytes", necessary in Python3

In [34]:
x

b'1234'

```
x is a string (in Python 3 a bytes), we can represent its data as an array of ints:
```

In [35]:
y = np.frombuffer?

In [36]:
# Interpret a buffer as a 1-dimensional array.
y = np.frombuffer(x, dtype=np.int8)
y

array([49, 50, 51, 52], dtype=int8)

In [37]:
y.data

In [38]:
y.base is x

True

In [39]:
y.flags

  C_CONTIGUOUS : True
  F_CONTIGUOUS : True
  OWNDATA : False
  WRITEABLE : False
  ALIGNED : True
  UPDATEIFCOPY : False

In [43]:
y.__array_interface__

{'data': (140706436955824, True),
 'descr': [('', '|i1')],
 'shape': (4,),
 'strides': None,
 'typestr': '|i1',
 'version': 3}

```
The owndata and writeable flags indicate status of the memory block.
```

### Data types

##### The descriptor

```
dtype describes a single item in the array:
```

In [44]:
np.dtype(int)

dtype('int64')

In [49]:
np.dtype(int).type # scalar type of the data

numpy.int64

In [50]:
np.dtype(int).itemsize # size of the data block

8

In [51]:
np.dtype(int).byteorder

'='